server:
  port: 10000

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/just3019/resConfig
eureka:
  client:
    enabled: false
